ignore:
  - "3DHistoGrading/Properties"
  - "3DHistoGrading/Program.cs$"
  - "3DHistoGrading/MainForm.cs$"
  - "3DHistoGrading/MainForm.Designer.cs$"
  
coverage:
  precision: 2
  round: down
  range: "50...100"
